# Generated by Django 4.2.5 on 2023-10-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_es_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='es_profesor',
            new_name='is_master',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='telefono',
            new_name='phone',
        ),
    ]
